In [1]:
%load_ext Cython
import numpy as np
import theano as th
import theano.tensor as T
import numba as nb
import math
import time

In [39]:
%%cython
from cython cimport boundscheck, wraparound
from cython.parallel cimport prange

cpdef void forLoop(float[:] f):
    cdef:
        int i, j, n
    n = f.shape[0]
    with boundscheck(False), wraparound(False):
        for j in prange(n, nogil=True):
            for i in range(100):
                f[j] = f[j] +1

In [46]:
a = np.ones(1000, dtype=np.float32)

In [47]:
b = a.copy()
%timeit forLoop(b)

14.4 µs ± 87.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
b = a.copy()
forLoop(b)
b

array([101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 10

In [49]:
ath = th.tensor.vector()
out = ath
for i in range(100):
    out += 1
f = th.function([ath], out)

In [50]:
b = a.copy()
%timeit f(b)

7.23 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
f(a)

array([101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 10

In [52]:
def forNumpy(a):
    for i in range(100):
        a += 1
    return a

In [53]:
b = a.copy()
%timeit forNumpy(b)

168 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
a = T.vector()
b = T.vector()
out = a + b
f = th.function([a, b], out)

In [3]:
@nb.vectorize(target='cpu')
def expon_cpu(x, y):
    return math.exp(x) + math.exp(y)

In [4]:
@nb.vectorize(['float32(float32, float32)'], target='cuda')
def expon_gpu(x, y):
    return math.exp(x) + math.exp(y)

In [8]:
N = 1000000
niter = 100
a = np.random.rand(N).astype('float32')
b = np.random.rand(N).astype('float32')
# Trigger compilation
expon_cpu(a, b)
#expon_gpu(a, b)
## Timing
start = time.time()
for i in range(niter):
    expon_cpu(a, b)
print("CPU:", time.time() - start)
start = time.time()
for i in range(niter):
    f(a, b)
print("theano:", time.time() - start)

CPU: 2.13869309425354
theano: 0.8225557804107666


In [19]:
a = T.vector()
b = T.vector()
c = (a > 0) * 2
f = th.function([a], c)

In [20]:
f([1, 0])

array([2, 0], dtype=int8)

In [23]:
T.ones((5, 5), dtype='uint8')

Alloc.0

In [31]:
a = th.shared([1, 2, 3])
y = T.vector()
b = (a, T.set_subtensor(a[0], y))
#b = (a, T.set_subtensor(a[0], 2))
#f = th.function([b], a)

TypeError: The generic 'SharedVariable' object is not subscriptable. This shared variable contains an object of type: <class 'list'>. Did you forget to cast it into a Numpy array before calling theano.shared()?

In [61]:
from theano import tensor as T
from theano import function, shared

ar = np.array([0,1,2,3,4])
X = shared(ar)
Y = T.ones(1) * 100
X_update = (X, T.set_subtensor(X[2:3], Y))
f = function([], updates=[X_update])
f()
#print X.get_value() # [0 1 100 10 4]



[]

In [60]:
X.get_value()

array([0, 1, 2, 3, 4])